# POC-Agent-AI-ouvertures-echecs-FFE/docker-compose.yml

# version: '3.9'

services:
  backend:
    build: ./backend
    container_name: fastapi_app

    ports:
      - "${BACKEND_PORT:-8000}:${BACKEND_PORT:-8000}"

    env_file:
      - .env

    depends_on:
      - milvus

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT:-8000}/docs"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: angular_app

    ports:
      - "${FRONTEND_PORT:-4200}:4200"

    volumes:
      - ./frontend:/app

    command: sh -c "npm install && npm run start"

    depends_on:
      - backend

    restart: unless-stopped

    networks:
      - app-network

  # 🔥 AJOUT RAG
  milvus:
    image: milvusdb/milvus:v2.3.3
    container_name: milvus

    ports:
      - "19530:19530"

    environment:
      - ETCD_USE_EMBED=true

    restart: unless-stopped

    networks:
      - app-network

networks:
  app-network:
